name: Convert Markdown to DOCX

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Markdown to DOCX
        uses: docker://pandoc/core:2.9
        with:
          args: "cv.md -o cv.docx"

      - name: Check Git Status
        run: git status

      - name: Commit and Push DOCX
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add cv.docx
          git commit -m "Add generated cv.docx" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DOCX as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-docx
          path: cv.docx
