name: Convert Markdown to DOCX

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: git clone https://github.com/utlandingur/utlandingur.git .
      
      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to DOCX
        run: pandoc cv.md -o cv.docx

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"

      - name: Commit and push changes
        run: |
          git add cv.docx
          git commit -m "Add generated cv.docx" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/utlandingur/utlandingur.git HEAD:main

      - name: Upload DOCX
        run: |
          mkdir -p output
          mv cv.docx output/
          echo "Output file available at output/cv.docx"
